model:
  id: meta-llama/Meta-Llama-3-8B-Instruct

index_datasets: [nq, musique, hotpotqa, trivia, 2wikimultihopqa]

retrieval:
  is_sparse: true
  is_cot: true

build_dataset:
  datasets: [nq, hotpotqa, trivia]
  steps_limit_train: 3000
  steps_limit_dev: 500
  sep_number: 0

train:
  method: tokens_mean
  batch_size: 6
  lr: 0.001
  epochs: 2
  layers: [12, 16, 20, 24, 28, 32]
  device: cuda:0
  train_ds_ratio: 1.0

prober:
  ds: 3
  ablation: 0

evaluate:
  datasets: [nq, musique, hotpotqa, trivia, 2wikimultihopqa]
  methods: [none, simple, probing, skillrag]
  steps_limit: 500
  threshold: 0.0
  position: resid_post
  max_retrieval_rounds: 3
  tr_or_dev: dev
  extracting_cot_qa: true
  extract_sep: true
  sep_number: 0
